### PR TITLE
Added .gitignore to get rid of all unnecessary files

### PR DESCRIPTION
**Pull request by arthur-here**

### CODE REVIEW

**Comment by Somnibyte** [comment]
Thank you for your help @burntheroad! :+1:

**Comment by Somnibyte** [comment]
Hey @burntheroad I made a mistake (I'm new to Git) can you make another pull request again?

**Comment by Somnibyte** [comment]
With the same updates.

**Comment by Somnibyte** [comment]
I apologize.

**Comment by arthur-here** [comment]
Sure, no problem. I've opened new PR

**Comment by Somnibyte** [comment]
Thank you @burntheroad. Can you also send the other pull request? The accidental forced push removed both of your pull requests earlier. I just added the new one you just sent.

**Comment by Somnibyte** [comment]
The "Some improvements to project structure" pull request is the one I need.

**Pull request merged**
